from django.test import TestCase
from .models import NetworkProblem
from django.utils.translation import gettext_lazy as _

# Create your tests here.
network_problems = [
    {'en': 'slow internet speed', 'ar': 'بطء سرعة الإنترنت', 'solution': {'en': 'Slow internet speed can be caused by a number of factors, such as congestion in your network, distance from the router, outdated firmware, or interference from other electronic devices. Try resetting your modem and router, moving closer to the router, updating firmware or adding a range extender. If the issue persists, contact your internet service provider.', 'ar': 'يمكن أن يكون بطء الإنترنت بسبب الازدحام في الشبكة، المسافة من جهاز التوجيه، البرامج الثابتة القديمة، أو التداخل من أجهزة إلكترونية أخرى. حاول إعادة تشغيل جهاز التوجيه والمودم الخاص بك، والتحرك إلى مكان أقرب إلى جهاز التوجيه، وتحديث البرامج الثابتة، أو إضافة مكبر نطاق. إذا استمرت المشكلة، يرجى الاتصال بمزود الإنترنت الخاص بك.'}},
    {'en': 'Wi-Fi network keeps dropping', 'ar': 'انقطاع شبكة الواي فاي', 'solution': {'en': 'Wi-Fi network drops can be caused by interference from other electronic devices, outdated router firmware, or configuration issues. Try relocating your router, updating the firmware, or changing the channel on which your Wi-Fi network operates. You can also try changing the security protocol or resetting the network settings on your device.', 'ar': 'يمكن أن يكون انقطاع شبكة الواي فاي بسبب التداخل من أجهزة إلكترونية أخرى، البرامج الثابتة القديمة لجهاز التوجيه، أو مشكلات التكوين. حاول نقل جهاز التوجيه الخاص بك، تحديث البرامج الثابتة، أو تغيير القناة التي تعمل عليها شبكة الواي فاي. يمكنك أيضًا تغيير بروتوكول الأمان أو إعادة ضبط إعدادات الشبكة على جهازك.'}},
    {'en': 'unable to access certain websites', 'ar': 'عدم القدرة على الوصول إلى مواقع معينة', 'solution': {'en': 'Inability to access certain websites can be caused by DNS server issues, misconfigured firewalls, or outdated web browsers. Try clearing your browser cache and cookies, disabling your firewall, or using a different web browser. If the issue persists, try changing your DNS server settings.', 'ar': 'عدم القدرة على الوصول إلى مواقع معينة يمكن أن يكون بسبب مشاكل خادم DNS، أو حماية الشبكة غير المكونة بشكل صحيح، أو متصفحات ويب قديمة. حاول مسح ذاكرة التخزين المؤقت والملفات المؤقتة لمتصفحك، وتعطيل حماية الشبكة، أو استخدام متصفح ويب مختلف. إذا استمرت المشكلة، حاول تغيير إعدادات خادم DNS.'}},
    {'en': 'unable to connect to the internet', 'ar': 'عدم القدرة على الاتصال بالإنترنت', 'solution': {'en': 'Inability to connect to the internet can be caused by a number of factors, such as a faulty modem, outdated router firmware, or a problem with your ISP. Try resetting your modem and router, updating the firmware, or contacting your ISP.', 'ar': 'عدم القدرة على الاتصال بالإنترنت يمكن أن يكون بسبب عدة عوامل، مثل مودم معطل، أو البرامج الثابتة القديمة لجهاز التوجيه، أو مشكلة مع مزود الإنترنت الخاص بك. حاول إعادة تشغيل جهاز التوجيه والمودم الخاص بك، وتحديث البرامج الثابتة، أو الاتصال بمزود الإنترنت الخاص بك.'}},
    {'en': 'unable to connect to Wi-Fi network', 'ar': 'عدم القدرة على الاتصال بشبكة الواي فاي', 'solution': {'en': 'Inability to connect to Wi-Fi network can be caused by a number of factors, such as a faulty router, outdated router firmware, or a problem with your ISP. Try resetting your router, updating the firmware, or contacting your ISP.', 'ar': 'عدم القدرة على الاتصال بشبكة الواي فاي يمكن أن يكون بسبب عدة عوامل، مثل جهاز التوجيه معطل، أو البرامج الثابتة القديمة لجهاز التوجيه، أو مشكلة مع مزود الإنترنت الخاص بك. حاول إعادة تشغيل جهاز التوجيه الخاص بك، وتحديث البرامج الثابتة، أو الاتصال بمزود الإنترنت الخاص بك.'}},
    {'en': 'unable to connect to a specific Wi-Fi network', 'ar': 'عدم القدرة على الاتصال بشبكة واي فاي معينة', 'solution': {'en': 'Inability to connect to a specific Wi-Fi network can be caused by a number of factors, such as a faulty router, outdated router firmware, or a problem with your ISP. Try resetting your router, updating the firmware, or contacting your ISP.', 'ar': 'عدم القدرة على الاتصال بشبكة واي فاي معينة يمكن أن يكون بسبب عدة عوامل، مثل جهاز التوجيه معطل، أو البرامج الثابتة القديمة لجهاز التوجيه، أو مشكلة مع مزود الإنترنت الخاص بك. حاول إعادة تشغيل جهاز التوجيه الخاص بك، وتحديث البرامج الثابتة، أو الاتصال بمزود الإنترنت الخاص بك.'}},
    
]
