# Generated by Django 4.1.7 on 2023-03-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
