# Generated by Django 4.1.7 on 2023-03-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255)),
                ('solution', models.TextField()),
            ],
        ),
    ]
