# Generated by Django 4.1.7 on 2023-03-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='solutions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
